heat_template_version: 2015-04-30

parameters:

  template_VirtualNetwork_1:
    type: string
    description: Name of management network to be created
  template_VirtualNetwork_2:
    type: string
    description: Name of left network to be created
  template_VirtualNetwork_3:
    type: string
    description: Name of right network to be created

  svm_name:
    type: string
    description: Name of the SVM
  flavor:
    type: string
    description: Flavor of the end VMs
  image:
    type: string
    description: Name of the end VM image

# Sub-Interface


  sub_interface_vlan_tag:
    type: number
    description: logical_interface_vlan_tag for the LogicalInterface
  name:
    type: string
    description: Name of the Sub-Interface
  instance_ip_1:
    type: string
    description: instance_ip_address for the InstanceIp


resources:

  template_VirtualMachineInterface_1:
    type: OS::ContrailV2::VirtualMachineInterface
    properties:
      virtual_machine_interface_properties:
        {
          virtual_machine_interface_properties_service_interface_type: { get_param: template_VirtualNetwork_1 },
        }
      virtual_network_refs: [{ get_param: template_VirtualNetwork_1 }]

  template_VirtualMachineInterface_2:
    type: OS::ContrailV2::VirtualMachineInterface
    properties:
      virtual_machine_interface_properties:
        {
          virtual_machine_interface_properties_service_interface_type: { get_param: template_VirtualNetwork_2 },
        }
      virtual_network_refs: [{ get_param: template_VirtualNetwork_2 }]

  template_VirtualMachineInterface_2_1:
    type: OS::ContrailV2::VirtualMachineInterface
    properties:
      display_name: { get_param: name }
      virtual_machine_interface_properties:
        {
          virtual_machine_interface_properties_sub_interface_vlan_tag: { get_param: sub_interface_vlan_tag },
        }
      virtual_network_refs: [{ get_param: template_VirtualNetwork_2 }]
      virtual_machine_interface_refs: [{ get_resource: template_VirtualMachineInterface_2 }]

  template_VirtualMachineInterface_3:
    type: OS::ContrailV2::VirtualMachineInterface
    properties:
      virtual_machine_interface_properties:
        {
          virtual_machine_interface_properties_service_interface_type: { get_param: template_VirtualNetwork_3 },
        }
      virtual_network_refs: [{ get_param: template_VirtualNetwork_3 }]

  template_InstanceIp_1:
    type: OS::ContrailV2::InstanceIp
    depends_on: [ template_VirtualMachineInterface_1 ]
    properties:
      virtual_machine_interface_refs: [{ get_resource: template_VirtualMachineInterface_1 }]
      virtual_network_refs: [{ get_param: template_VirtualNetwork_1 }]

  template_InstanceIp_2:
    type: OS::ContrailV2::InstanceIp
    depends_on: [ template_VirtualMachineInterface_2 ]
    properties:
      virtual_machine_interface_refs: [{ get_resource: template_VirtualMachineInterface_2 }]
      virtual_network_refs: [{ get_param: template_VirtualNetwork_2 }]

  template_InstanceIp_2_1:
    type: OS::ContrailV2::InstanceIp
    depends_on: [ template_VirtualMachineInterface_2_1 ]
    properties:
      virtual_machine_interface_refs: [{ get_resource: template_VirtualMachineInterface_2_1 }]
      virtual_network_refs: [{ get_param: template_VirtualNetwork_2 }]
      instance_ip_address: { get_param: instance_ip_1 }

  template_InstanceIp_3:
    type: OS::ContrailV2::InstanceIp
    depends_on: [ template_VirtualMachineInterface_3 ]
    properties:
      virtual_machine_interface_refs: [{ get_resource: template_VirtualMachineInterface_3 }]
      virtual_network_refs: [{ get_param: template_VirtualNetwork_3 }]

  instance:
    type: OS::Nova::Server
    depends_on: [ template_InstanceIp_1, template_InstanceIp_2, template_InstanceIp_2_1, template_InstanceIp_3 ]
    properties:
      name: {get_param: svm_name }
      image: { get_param:  image }
      flavor: { get_param: flavor }
      networks:
        - port: { get_resource: template_VirtualMachineInterface_1 }
        - port: { get_resource: template_VirtualMachineInterface_2 }
        - port: { get_resource: template_VirtualMachineInterface_3 }


